swagger: "2.0"
info:
  title: "Employee Management System"
  version: "1.0"
  description: "This is a sample server which performs REST operations."
  contact: {}
host: "localhost:8080"
basePath: "/employees"
schemes:
  - "http"
paths:
  /login:
    post:
      summary: "Login"
      description: "Authenticate user"
      tags:
        - authentication
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: "Login credentials"
          required: true
          schema:
            $ref: "#/definitions/LoginRequest"
      responses:
        "200":
          description: "Authentication successful"
          schema:
            $ref: "#/definitions/Employee"
        "401":
          description: "Unauthorized"
  /:
    get:
      summary: "Get all employees"
      tags:
        - employees
      produces:
        - application/json
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Employee"
        "500":
          description: "Internal Server Error"
    post:
      summary: "Create an employee"
      tags:
        - employees
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: "Employee object"
          required: true
          schema:
            $ref: "#/definitions/Employee"
      responses:
        "201":
          description: "Employee created successfully"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"
  /{id}:
    get:
      summary: "Get employee by ID"
      tags:
        - employees
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          format: int64
      produces:
        - application/json
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Employee"
        "400":
          description: "Bad Request"
        "404":
          description: "Employee not found"
        "500":
          description: "Internal Server Error"
    put:
      summary: "Update employee by ID"
      tags:
        - employees
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: "Updated employee object"
          required: true
          schema:
            $ref: "#/definitions/Employee"
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: "Employee updated successfully"
        "400":
          description: "Bad Request"
        "404":
          description: "Employee not found"
        "500":
          description: "Internal Server Error"
    delete:
      summary: "Delete employee by ID"
      tags:
        - employees
      parameters:
        - in: path
          name: id
          required: true
          type: integer
          format: int64
      produces:
        - application/json
      responses:
        "200":
          description: "Employee deleted successfully"
        "400":
          description: "Bad Request"
        "404":
          description: "Employee not found"
        "500":
          description: "Internal Server Error"
  /search:
    get:
      summary: "Search employees"
      tags:
        - employees
      parameters:
        - in: query
          name: field
          required: true
          type: string
        - in: query
          name: value
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Employee"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"
definitions:
  LoginRequest:
    type: object
    properties:
      Email:
        type: string
      Password:
        type: string
  Employee:
    type: object
    properties:
      ID:
        type: integer
        format: int64
      FirstName:
        type: string
      LastName:
        type: string
      Email:
        type: string
      Role:
        type: string
